import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import Script from "next/script";

export const metadata: Metadata = {
  title: "New App",
  description: "Generated by SteerCode",
  authors: [{ name: "SteerCode", url: "https://steercode.com" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>{children}</main>
          <Toaster />
          <Script src="https://steercode.web.app/steercode.min.js" type="module" strategy="beforeInteractive" />
        </ThemeProvider>
      </body>
    </html>
  );
}
